// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.6.1
// source: logistica.proto

package logistica

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Definimos el request del enviopaquete
type PaqueteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdPaquete string `protobuf:"bytes,1,opt,name=idPaquete,proto3" json:"idPaquete,omitempty"`
	Tipo      int32  `protobuf:"varint,2,opt,name=tipo,proto3" json:"tipo,omitempty"`    //0=es retail, 1=pyme, 2=prioritario
	Nombre    string `protobuf:"bytes,3,opt,name=nombre,proto3" json:"nombre,omitempty"` //nombre producto
	Valor     int32  `protobuf:"varint,4,opt,name=valor,proto3" json:"valor,omitempty"`
	Origen    string `protobuf:"bytes,5,opt,name=origen,proto3" json:"origen,omitempty"`
	Destino   string `protobuf:"bytes,6,opt,name=destino,proto3" json:"destino,omitempty"`
}

func (x *PaqueteRequest) Reset() {
	*x = PaqueteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logistica_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaqueteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaqueteRequest) ProtoMessage() {}

func (x *PaqueteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logistica_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaqueteRequest.ProtoReflect.Descriptor instead.
func (*PaqueteRequest) Descriptor() ([]byte, []int) {
	return file_logistica_proto_rawDescGZIP(), []int{0}
}

func (x *PaqueteRequest) GetIdPaquete() string {
	if x != nil {
		return x.IdPaquete
	}
	return ""
}

func (x *PaqueteRequest) GetTipo() int32 {
	if x != nil {
		return x.Tipo
	}
	return 0
}

func (x *PaqueteRequest) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *PaqueteRequest) GetValor() int32 {
	if x != nil {
		return x.Valor
	}
	return 0
}

func (x *PaqueteRequest) GetOrigen() string {
	if x != nil {
		return x.Origen
	}
	return ""
}

func (x *PaqueteRequest) GetDestino() string {
	if x != nil {
		return x.Destino
	}
	return ""
}

// Definimos el response del enviopaquete
type PaqueteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NumSeguimiento string `protobuf:"bytes,1,opt,name=numSeguimiento,proto3" json:"numSeguimiento,omitempty"`
}

func (x *PaqueteResponse) Reset() {
	*x = PaqueteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logistica_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaqueteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaqueteResponse) ProtoMessage() {}

func (x *PaqueteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_logistica_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaqueteResponse.ProtoReflect.Descriptor instead.
func (*PaqueteResponse) Descriptor() ([]byte, []int) {
	return file_logistica_proto_rawDescGZIP(), []int{1}
}

func (x *PaqueteResponse) GetNumSeguimiento() string {
	if x != nil {
		return x.NumSeguimiento
	}
	return ""
}

//definimos el request del servicio de seguimiento del paquete
type SeguimientoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NumSeguimiento string `protobuf:"bytes,1,opt,name=numSeguimiento,proto3" json:"numSeguimiento,omitempty"`
}

func (x *SeguimientoRequest) Reset() {
	*x = SeguimientoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logistica_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SeguimientoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeguimientoRequest) ProtoMessage() {}

func (x *SeguimientoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logistica_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeguimientoRequest.ProtoReflect.Descriptor instead.
func (*SeguimientoRequest) Descriptor() ([]byte, []int) {
	return file_logistica_proto_rawDescGZIP(), []int{2}
}

func (x *SeguimientoRequest) GetNumSeguimiento() string {
	if x != nil {
		return x.NumSeguimiento
	}
	return ""
}

//definimos el response del servicio de seguimiento del paquete
type SeguimientoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Estado string `protobuf:"bytes,1,opt,name=estado,proto3" json:"estado,omitempty"`
}

func (x *SeguimientoResponse) Reset() {
	*x = SeguimientoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logistica_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SeguimientoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeguimientoResponse) ProtoMessage() {}

func (x *SeguimientoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_logistica_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeguimientoResponse.ProtoReflect.Descriptor instead.
func (*SeguimientoResponse) Descriptor() ([]byte, []int) {
	return file_logistica_proto_rawDescGZIP(), []int{3}
}

func (x *SeguimientoResponse) GetEstado() string {
	if x != nil {
		return x.Estado
	}
	return ""
}

type InformeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Entregado bool   `protobuf:"varint,2,opt,name=entregado,proto3" json:"entregado,omitempty"`
}

func (x *InformeRequest) Reset() {
	*x = InformeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logistica_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InformeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InformeRequest) ProtoMessage() {}

func (x *InformeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logistica_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InformeRequest.ProtoReflect.Descriptor instead.
func (*InformeRequest) Descriptor() ([]byte, []int) {
	return file_logistica_proto_rawDescGZIP(), []int{4}
}

func (x *InformeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InformeRequest) GetEntregado() bool {
	if x != nil {
		return x.Entregado
	}
	return false
}

type InformeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Recibido bool `protobuf:"varint,1,opt,name=recibido,proto3" json:"recibido,omitempty"`
}

func (x *InformeResponse) Reset() {
	*x = InformeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logistica_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InformeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InformeResponse) ProtoMessage() {}

func (x *InformeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_logistica_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InformeResponse.ProtoReflect.Descriptor instead.
func (*InformeResponse) Descriptor() ([]byte, []int) {
	return file_logistica_proto_rawDescGZIP(), []int{5}
}

func (x *InformeResponse) GetRecibido() bool {
	if x != nil {
		return x.Recibido
	}
	return false
}

type RepartoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdCamion int32 `protobuf:"varint,1,opt,name=idCamion,proto3" json:"idCamion,omitempty"`
}

func (x *RepartoRequest) Reset() {
	*x = RepartoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logistica_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RepartoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepartoRequest) ProtoMessage() {}

func (x *RepartoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logistica_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepartoRequest.ProtoReflect.Descriptor instead.
func (*RepartoRequest) Descriptor() ([]byte, []int) {
	return file_logistica_proto_rawDescGZIP(), []int{6}
}

func (x *RepartoRequest) GetIdCamion() int32 {
	if x != nil {
		return x.IdCamion
	}
	return 0
}

type RepartoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Tipo    int32  `protobuf:"varint,2,opt,name=tipo,proto3" json:"tipo,omitempty"` //0=es retail, 1=pyme, 2=prioritario
	Valor   int32  `protobuf:"varint,3,opt,name=valor,proto3" json:"valor,omitempty"`
	Origen  string `protobuf:"bytes,5,opt,name=origen,proto3" json:"origen,omitempty"`
	Destino string `protobuf:"bytes,6,opt,name=destino,proto3" json:"destino,omitempty"`
	Intento int32  `protobuf:"varint,7,opt,name=intento,proto3" json:"intento,omitempty"`
}

func (x *RepartoResponse) Reset() {
	*x = RepartoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logistica_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RepartoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepartoResponse) ProtoMessage() {}

func (x *RepartoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_logistica_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepartoResponse.ProtoReflect.Descriptor instead.
func (*RepartoResponse) Descriptor() ([]byte, []int) {
	return file_logistica_proto_rawDescGZIP(), []int{7}
}

func (x *RepartoResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RepartoResponse) GetTipo() int32 {
	if x != nil {
		return x.Tipo
	}
	return 0
}

func (x *RepartoResponse) GetValor() int32 {
	if x != nil {
		return x.Valor
	}
	return 0
}

func (x *RepartoResponse) GetOrigen() string {
	if x != nil {
		return x.Origen
	}
	return ""
}

func (x *RepartoResponse) GetDestino() string {
	if x != nil {
		return x.Destino
	}
	return ""
}

func (x *RepartoResponse) GetIntento() int32 {
	if x != nil {
		return x.Intento
	}
	return 0
}

var File_logistica_proto protoreflect.FileDescriptor

var file_logistica_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x6c, 0x6f, 0x67, 0x69, 0x73, 0x74, 0x69, 0x63, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x6c, 0x6f, 0x67, 0x69, 0x73, 0x74, 0x69, 0x63, 0x61, 0x22, 0xa2, 0x01, 0x0a,
	0x0e, 0x50, 0x61, 0x71, 0x75, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1c, 0x0a, 0x09, 0x69, 0x64, 0x50, 0x61, 0x71, 0x75, 0x65, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x69, 0x64, 0x50, 0x61, 0x71, 0x75, 0x65, 0x74, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x69, 0x70, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x69, 0x70,
	0x6f, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x6f, 0x72, 0x12,
	0x16, 0x0a, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x65, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x6f, 0x72, 0x69, 0x67, 0x65, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x73, 0x74, 0x69,
	0x6e, 0x6f, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e,
	0x6f, 0x22, 0x39, 0x0a, 0x0f, 0x50, 0x61, 0x71, 0x75, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x6e, 0x75, 0x6d, 0x53, 0x65, 0x67, 0x75, 0x69,
	0x6d, 0x69, 0x65, 0x6e, 0x74, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x6e, 0x75,
	0x6d, 0x53, 0x65, 0x67, 0x75, 0x69, 0x6d, 0x69, 0x65, 0x6e, 0x74, 0x6f, 0x22, 0x3c, 0x0a, 0x12,
	0x53, 0x65, 0x67, 0x75, 0x69, 0x6d, 0x69, 0x65, 0x6e, 0x74, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x26, 0x0a, 0x0e, 0x6e, 0x75, 0x6d, 0x53, 0x65, 0x67, 0x75, 0x69, 0x6d, 0x69,
	0x65, 0x6e, 0x74, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x6e, 0x75, 0x6d, 0x53,
	0x65, 0x67, 0x75, 0x69, 0x6d, 0x69, 0x65, 0x6e, 0x74, 0x6f, 0x22, 0x2d, 0x0a, 0x13, 0x53, 0x65,
	0x67, 0x75, 0x69, 0x6d, 0x69, 0x65, 0x6e, 0x74, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x65, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x22, 0x3e, 0x0a, 0x0e, 0x49, 0x6e, 0x66,
	0x6f, 0x72, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x65,
	0x6e, 0x74, 0x72, 0x65, 0x67, 0x61, 0x64, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09,
	0x65, 0x6e, 0x74, 0x72, 0x65, 0x67, 0x61, 0x64, 0x6f, 0x22, 0x2d, 0x0a, 0x0f, 0x49, 0x6e, 0x66,
	0x6f, 0x72, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x72, 0x65, 0x63, 0x69, 0x62, 0x69, 0x64, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08,
	0x72, 0x65, 0x63, 0x69, 0x62, 0x69, 0x64, 0x6f, 0x22, 0x2c, 0x0a, 0x0e, 0x52, 0x65, 0x70, 0x61,
	0x72, 0x74, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x64,
	0x43, 0x61, 0x6d, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x69, 0x64,
	0x43, 0x61, 0x6d, 0x69, 0x6f, 0x6e, 0x22, 0x97, 0x01, 0x0a, 0x0f, 0x52, 0x65, 0x70, 0x61, 0x72,
	0x74, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69,
	0x70, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x69, 0x70, 0x6f, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x6f, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x65, 0x6e, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x65, 0x6e, 0x12, 0x18, 0x0a, 0x07,
	0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x6f, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64,
	0x65, 0x73, 0x74, 0x69, 0x6e, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x6f, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x69, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x6f,
	0x32, 0xba, 0x02, 0x0a, 0x07, 0x50, 0x61, 0x71, 0x75, 0x65, 0x74, 0x65, 0x12, 0x46, 0x0a, 0x0d,
	0x45, 0x6e, 0x76, 0x69, 0x61, 0x72, 0x50, 0x61, 0x71, 0x75, 0x65, 0x74, 0x65, 0x12, 0x19, 0x2e,
	0x6c, 0x6f, 0x67, 0x69, 0x73, 0x74, 0x69, 0x63, 0x61, 0x2e, 0x50, 0x61, 0x71, 0x75, 0x65, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x73,
	0x74, 0x69, 0x63, 0x61, 0x2e, 0x50, 0x61, 0x71, 0x75, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x53, 0x0a, 0x12, 0x53, 0x65, 0x67, 0x75, 0x69, 0x6d, 0x69, 0x65,
	0x6e, 0x74, 0x6f, 0x50, 0x61, 0x71, 0x75, 0x65, 0x74, 0x65, 0x12, 0x1d, 0x2e, 0x6c, 0x6f, 0x67,
	0x69, 0x73, 0x74, 0x69, 0x63, 0x61, 0x2e, 0x53, 0x65, 0x67, 0x75, 0x69, 0x6d, 0x69, 0x65, 0x6e,
	0x74, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x6c, 0x6f, 0x67, 0x69,
	0x73, 0x74, 0x69, 0x63, 0x61, 0x2e, 0x53, 0x65, 0x67, 0x75, 0x69, 0x6d, 0x69, 0x65, 0x6e, 0x74,
	0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x49, 0x0a, 0x10, 0x53, 0x6f, 0x6c,
	0x69, 0x63, 0x69, 0x74, 0x75, 0x64, 0x50, 0x61, 0x71, 0x75, 0x65, 0x74, 0x65, 0x12, 0x19, 0x2e,
	0x6c, 0x6f, 0x67, 0x69, 0x73, 0x74, 0x69, 0x63, 0x61, 0x2e, 0x52, 0x65, 0x70, 0x61, 0x72, 0x74,
	0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x73,
	0x74, 0x69, 0x63, 0x61, 0x2e, 0x52, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6f, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x47, 0x0a, 0x0e, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x65, 0x52,
	0x65, 0x70, 0x61, 0x72, 0x74, 0x6f, 0x12, 0x19, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x73, 0x74, 0x69,
	0x63, 0x61, 0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1a, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x73, 0x74, 0x69, 0x63, 0x61, 0x2e, 0x49, 0x6e,
	0x66, 0x6f, 0x72, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_logistica_proto_rawDescOnce sync.Once
	file_logistica_proto_rawDescData = file_logistica_proto_rawDesc
)

func file_logistica_proto_rawDescGZIP() []byte {
	file_logistica_proto_rawDescOnce.Do(func() {
		file_logistica_proto_rawDescData = protoimpl.X.CompressGZIP(file_logistica_proto_rawDescData)
	})
	return file_logistica_proto_rawDescData
}

var file_logistica_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_logistica_proto_goTypes = []interface{}{
	(*PaqueteRequest)(nil),      // 0: logistica.PaqueteRequest
	(*PaqueteResponse)(nil),     // 1: logistica.PaqueteResponse
	(*SeguimientoRequest)(nil),  // 2: logistica.SeguimientoRequest
	(*SeguimientoResponse)(nil), // 3: logistica.SeguimientoResponse
	(*InformeRequest)(nil),      // 4: logistica.InformeRequest
	(*InformeResponse)(nil),     // 5: logistica.InformeResponse
	(*RepartoRequest)(nil),      // 6: logistica.RepartoRequest
	(*RepartoResponse)(nil),     // 7: logistica.RepartoResponse
}
var file_logistica_proto_depIdxs = []int32{
	0, // 0: logistica.Paquete.EnviarPaquete:input_type -> logistica.PaqueteRequest
	2, // 1: logistica.Paquete.SeguimientoPaquete:input_type -> logistica.SeguimientoRequest
	6, // 2: logistica.Paquete.SolicitudPaquete:input_type -> logistica.RepartoRequest
	4, // 3: logistica.Paquete.InformeReparto:input_type -> logistica.InformeRequest
	1, // 4: logistica.Paquete.EnviarPaquete:output_type -> logistica.PaqueteResponse
	3, // 5: logistica.Paquete.SeguimientoPaquete:output_type -> logistica.SeguimientoResponse
	7, // 6: logistica.Paquete.SolicitudPaquete:output_type -> logistica.RepartoResponse
	5, // 7: logistica.Paquete.InformeReparto:output_type -> logistica.InformeResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_logistica_proto_init() }
func file_logistica_proto_init() {
	if File_logistica_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_logistica_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaqueteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logistica_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaqueteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logistica_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SeguimientoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logistica_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SeguimientoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logistica_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InformeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logistica_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InformeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logistica_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RepartoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logistica_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RepartoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_logistica_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_logistica_proto_goTypes,
		DependencyIndexes: file_logistica_proto_depIdxs,
		MessageInfos:      file_logistica_proto_msgTypes,
	}.Build()
	File_logistica_proto = out.File
	file_logistica_proto_rawDesc = nil
	file_logistica_proto_goTypes = nil
	file_logistica_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PaqueteClient is the client API for Paquete service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PaqueteClient interface {
	EnviarPaquete(ctx context.Context, in *PaqueteRequest, opts ...grpc.CallOption) (*PaqueteResponse, error)
	SeguimientoPaquete(ctx context.Context, in *SeguimientoRequest, opts ...grpc.CallOption) (*SeguimientoResponse, error)
	SolicitudPaquete(ctx context.Context, in *RepartoRequest, opts ...grpc.CallOption) (*RepartoResponse, error)
	InformeReparto(ctx context.Context, in *InformeRequest, opts ...grpc.CallOption) (*InformeResponse, error)
}

type paqueteClient struct {
	cc grpc.ClientConnInterface
}

func NewPaqueteClient(cc grpc.ClientConnInterface) PaqueteClient {
	return &paqueteClient{cc}
}

func (c *paqueteClient) EnviarPaquete(ctx context.Context, in *PaqueteRequest, opts ...grpc.CallOption) (*PaqueteResponse, error) {
	out := new(PaqueteResponse)
	err := c.cc.Invoke(ctx, "/logistica.Paquete/EnviarPaquete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paqueteClient) SeguimientoPaquete(ctx context.Context, in *SeguimientoRequest, opts ...grpc.CallOption) (*SeguimientoResponse, error) {
	out := new(SeguimientoResponse)
	err := c.cc.Invoke(ctx, "/logistica.Paquete/SeguimientoPaquete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paqueteClient) SolicitudPaquete(ctx context.Context, in *RepartoRequest, opts ...grpc.CallOption) (*RepartoResponse, error) {
	out := new(RepartoResponse)
	err := c.cc.Invoke(ctx, "/logistica.Paquete/SolicitudPaquete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paqueteClient) InformeReparto(ctx context.Context, in *InformeRequest, opts ...grpc.CallOption) (*InformeResponse, error) {
	out := new(InformeResponse)
	err := c.cc.Invoke(ctx, "/logistica.Paquete/InformeReparto", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaqueteServer is the server API for Paquete service.
type PaqueteServer interface {
	EnviarPaquete(context.Context, *PaqueteRequest) (*PaqueteResponse, error)
	SeguimientoPaquete(context.Context, *SeguimientoRequest) (*SeguimientoResponse, error)
	SolicitudPaquete(context.Context, *RepartoRequest) (*RepartoResponse, error)
	InformeReparto(context.Context, *InformeRequest) (*InformeResponse, error)
}

// UnimplementedPaqueteServer can be embedded to have forward compatible implementations.
type UnimplementedPaqueteServer struct {
}

func (*UnimplementedPaqueteServer) EnviarPaquete(context.Context, *PaqueteRequest) (*PaqueteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnviarPaquete not implemented")
}
func (*UnimplementedPaqueteServer) SeguimientoPaquete(context.Context, *SeguimientoRequest) (*SeguimientoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SeguimientoPaquete not implemented")
}
func (*UnimplementedPaqueteServer) SolicitudPaquete(context.Context, *RepartoRequest) (*RepartoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SolicitudPaquete not implemented")
}
func (*UnimplementedPaqueteServer) InformeReparto(context.Context, *InformeRequest) (*InformeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InformeReparto not implemented")
}

func RegisterPaqueteServer(s *grpc.Server, srv PaqueteServer) {
	s.RegisterService(&_Paquete_serviceDesc, srv)
}

func _Paquete_EnviarPaquete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaqueteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaqueteServer).EnviarPaquete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/logistica.Paquete/EnviarPaquete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaqueteServer).EnviarPaquete(ctx, req.(*PaqueteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Paquete_SeguimientoPaquete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SeguimientoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaqueteServer).SeguimientoPaquete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/logistica.Paquete/SeguimientoPaquete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaqueteServer).SeguimientoPaquete(ctx, req.(*SeguimientoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Paquete_SolicitudPaquete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RepartoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaqueteServer).SolicitudPaquete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/logistica.Paquete/SolicitudPaquete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaqueteServer).SolicitudPaquete(ctx, req.(*RepartoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Paquete_InformeReparto_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InformeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaqueteServer).InformeReparto(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/logistica.Paquete/InformeReparto",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaqueteServer).InformeReparto(ctx, req.(*InformeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Paquete_serviceDesc = grpc.ServiceDesc{
	ServiceName: "logistica.Paquete",
	HandlerType: (*PaqueteServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EnviarPaquete",
			Handler:    _Paquete_EnviarPaquete_Handler,
		},
		{
			MethodName: "SeguimientoPaquete",
			Handler:    _Paquete_SeguimientoPaquete_Handler,
		},
		{
			MethodName: "SolicitudPaquete",
			Handler:    _Paquete_SolicitudPaquete_Handler,
		},
		{
			MethodName: "InformeReparto",
			Handler:    _Paquete_InformeReparto_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "logistica.proto",
}
